parameters:
    app.path.csv_files: public/uploads/files
vich_uploader:
    db_driver: orm
    mappings:
        csv_files:
            uri_prefix: '%app.path.csv_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.csv_files%'

