parameters:
    app.path.csv_files: /uploads/files
    app.path.profile_pics: /uploads/images
vich_uploader:
    metadata:
        type: attribute
    db_driver: orm
    mappings:
        csv_files:
            uri_prefix: '%app.path.csv_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.csv_files%'
        profile_pics:
            uri_prefix: '%app.path.profile_pics%'
            upload_destination: '%kernel.project_dir%/public%app.path.profile_pics%'

